---
- name: upload image to ECR
  uses: appleboy/docker-ecr-action@master
  with:
    access_key: ${{secrets.ACCESS_KEY}}
    secret_key: ${{secrets.ECR_TEST}}
    repo: node-test
    registry: 367509475958.dkr.ecr.eu-west-3.amazonaws.com
